name: Daily Vercel Deployment

on:
  schedule:
    # Runs every day at 08:00 UTC
    - cron: '0 8 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trigger Vercel Deployment
      run: curl -X POST -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" |
        https://api.vercel.com/v1/integrations/deploy/prj_JoW7TZ0gcjEY3BWXdIuxSw0jcsZh